export const CHECK_LOGIN_STARTED = 'CHECK_LOGIN_STARTED';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_LOGOUT = 'CHECK_LOGIN_LOGOUT';
export const CHECK_LOGIN_FAILURE = 'CHECK_LOGIN_FAILURE';
export const CHECK_LOGIN_RESET = 'CHECK_LOGIN_RESET';
export const GET_LOGIN_DATA = 'GET_LOGIN_DATA';

export const CHECK_LOGGED = 'CHECK_LOGGED';

export const LOGOUT_APP = 'LOGOUT_APP';


export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';